<x-layout.main>
    <!-- Aside -->
    <aside id="link-menu" class="d-none col-md-3 rounded-3 p-3 position-fixed end-0 me-5">
        <h3>Useful links</h3>
        <hr>
        <ul class="list-unstyled d-flex flex-column gap-3 m-0">
            <li>
                <a href="https://oer.hz.nl/6978cdea-fb31-430b-9bf9-63206aa07754">
                    The HZ HBO-ICT Course and Examination Regulations (CER)
                </a>
            </li>
            <li>
                <a href="https://hz.nl/uploads/documents/1.4-Over-de-HZ/1.4.3.-Regelingen-en-documenten/OERS/2023-2024/Juli/CER-HZ-Bachelor-full-time-2023-2024-DEF-version-20240412.pdf?_gl=1*1us1txq*_up*MQ..&gclid=Cj0KCQjwiuC2BhDSARIsALOVfBKurbY7bDLmshx8x2BGn1gRz97T8jy3Tz_x_yvpk8ipMFH4tgeMWnEaAt2hEALw_wcB">The
                    Implementation Regulations (IR) of the HBO-ICT program
                </a>
            </li>
            <li><a href="https://learn.hz.nl/my/">HZ Learn environment</a></li>
            <li><a href="https://hz.osiris-student.nl/voortgang">Study Progress</a></li>
            <li><a href="https://github.com/HZ-HBO-ICT">HZ Github</a></li>
        </ul>
    </aside>
    <section id="dashboard" class="page">
        <div>
            <section class="p-0">
                <div class="d-flex gap-3 align-items-center">
                    <h1 class="">Dashboard</h1>
                    <button id="link-button" onclick="openSideMenu()"
                            class="ghost-button fw-bold rounded-pill px-3 py-1 border-none">Open
                        links
                    </button>
                </div>
                <div id="table-wrapper" class="rounded-3 mt-2">
                    <!-- Table -->
                    <!-- Data within the table will be generated by dashboard-data.js -->
                    <table id="dashboard-table" class="rounded-3 w-100">
                        <thead>
                        <tr>
                            <th>Designation</th>
                            <th>Name</th>
                            <th>EC</th>
                            <th>Grade</th>
                            <th>Project</th>
                            <th>Quarter</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        @php $sumOfCredits = 0; @endphp
                        @foreach($courses as $course)
                            @php
                                // Check course state
                                $isCompleted = true;
                                $isGraded = false;
                                $onGoing = false;
                                $status = 'Not Started';
                                $statusClass = 'status-not-started';

                                foreach ($course->tests as $test) {
                                    if ($test['best_grade'] == 0) {
                                        $onGoing = true;
                                        continue;
                                    }
                                    if ($test['best_grade'] < 5.5) {
                                        $isCompleted = false;
                                    }
                                    if ($test['best_grade'] > 0) {
                                        $isGraded = true;
                                    }
                                }

                                if ($isGraded) {
                                    $status = "Ongoing";
                                    $statusClass = "status-unknown";
                                }
                                if (($isCompleted && $isGraded && !$onGoing)) {
                                    $status = "Completed";
                                    $statusClass = "status-completed";
                                    $sumOfCredits += $course->credits;
                                } elseif (!$isCompleted) {
                                    $status = "Failed";
                                    $statusClass = "status-failed";
                                }
                            @endphp
                            @if(count($course->tests) > 1)
                                <tr>
                                    <td>{{ $course->cu_code }}</td>
                                    <td>{{ $course->name }}</td>
                                    <td>{{ round($course->credits, 1) }}</td>
                                    <td></td>
                                    <td></td>
                                    <td>{{ $course->timing }}</td>
                                    <td class="status {{ $statusClass }}">{{ $status }}</td>
                                </tr>
                                @foreach($course->tests as $test)
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td>{{ round($test->credits, 1) }}</td>
                                        <td>{{ round($test->best_grade, 1) }}</td>
                                        <td>{{ $test->name }}</td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                @endforeach
                                {{--Only 1 test--}}
                            @else
                                <tr>
                                    <td>{{ $course->cu_code }}</td>
                                    <td>{{ $course->name }}</td>
                                    <td>{{ round($course->credits, 1) }}</td>
                                    <td>{{ round($course->tests[0]->best_grade, 1) }}</td>
                                    <td>{{ $course->tests[0]->name }}</td>
                                    <td>{{ $course->timing }}</td>
                                    <td class="status {{ $statusClass }}">{{ $status }}</td>
                                </tr>
                            @endif
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <br>
                <div id="progress-bar-rails" class="w-100 p-2 rounded-pill">
                    <div id="progress-bar" class="position-relative px-2 py-1 rounded-pill text-dark">
                    </div>
                </div>
                <span><span id="total-credits"></span>{{ $sumOfCredits }} / 60 EC's</span>
                <p class="m-0 float-end">Minimum credits required to pass (NBSA): 45 EC</p>
            </section>
        </div>
    </section>
    <script src="{{ asset('js/link-menu-toggle.js') }}"></script>
    <script>
        const progressBar = document.getElementById('progress-bar');
        const widthPercentage = ({{ $sumOfCredits }} / 60) * 100;
        progressBar.style.width = widthPercentage + '%';
    </script>
</x-layout.main>
